#!/bin/bash
echo making object files and executables...
make &>> /dev/null

echo running valgrind...
valgrind --leak-check=full --show-leak-kinds=all crawler test tester_dir 5

echo making clean...
make clean &>> /dev/null
